### ISSUE TITLE
Crashes with IndexOutOfBoundsException on reading.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pkern/kitcard-reader#5]
```
What steps will reproduce the problem?
1. Touch the card to my phone (running or not).

What is the expected output? What do you see instead?
I expect it to show my balance, instead it crashes :)

What version of the product are you using? On what operating system?
Galaxy Nexus phone, "Incremental Version": 398337


Please provide any additional information below.
I've sent an error report from within android, I assume you can see that 
somewhere, so I'll not go into details and copy-paste the stacktrace in here 
:). If you need any more details, reach out to me.
```

Original issue reported on code.google.com by `ps.si...@gmail.com` on 13 Sep 2012 at 3:03

**Comment by GoogleCodeExporter** [comment]
```
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.get(ArrayList.java:304)
at de.Ox539.kitcard.reader.Wallet.readCard(Wallet.java:55)
at de.Ox539.kitcard.reader.ReadCardTask.doInBackground(ReadCardTask.java:36)
at de.Ox539.kitcard.reader.ReadCardTask.doInBackground(ReadCardTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 5 more

I already suspected that from your description. It does mean that it did not 
find a data sector on the card that matches the vendor ID that's typically used 
by the wallet.

If you have a few minutes, I'd appreciate if you could install NFC TagInfo and 
look at the application directory of the card. Does the AID 8917 show up at 
all? Which AID does sector 6 have? (That's the place where the wallet is 
usually stored.)
```

Original comment by `philipp.kern` on 13 Sep 2012 at 3:44

**Comment by GoogleCodeExporter** [comment]
```
Sure,

I assume you mean this one: 
https://play.google.com/store/apps/details?id=at.mroland.android.apps.nfctaginfo
 and not the higher-ranked this one (where I coulnd't find anything about AIDs 
anywhere.)
https://play.google.com/store/apps/details?id=com.nxp.taginfolite ?


AID 8917 isn't present, only 3803 and 380A.
3803 is in sector 6 & 7 if I'm reading this correctly.

But if I go to "Data (HEX)" I get a read-failed.

I'm not entirely sure if I ever did that keychange (Thats what the "umkodieren" 
was, right?) that everyone had to go through at some point.

Let me know if I can do anything else.
```

Original comment by `ps.si...@gmail.com` on 13 Sep 2012 at 4:07

**Comment by GoogleCodeExporter** [comment]
```
Well, that was my guess, too. I didn't have an old card to test. The only thing 
that's supposed to be readable from old format cards is the card's number. I 
wonder if that's helpful at all, given that it's printed on the card anyway. 
How the wallet data is encoded is unknown and also hard to reverse engineer 
given that there are no devices around anymore that tamper with the state.

The "keychange" was in fact a format conversion. They read out the old wallet 
data and write their own wallet data block to the card (marked by application 
ID 8917). Given my current card, which does have 380A for the other data and no 
3803, I presume that the old wallet data was in fact marked with 3803 and in 
two sectors instead of one. So I guess if I encounter this I can be fairly sure 
that the card needs to be re-encoded and display a note about it. In any case 
the app must not crash.

Thanks for the help! I'm sorry that the app will be unable to present you your 
remaining balance.
```

Original comment by `philipp.kern` on 13 Sep 2012 at 8:41
- Changed state: **Accepted**
- Added labels: **Milestone-Release1.0**

**Comment by GoogleCodeExporter** [comment]
```
Revision a5d570591ceb adds code to detect this case and should show a message 
to the user that the cards needs to be re-encoded.

The attachment contains an interim release signed with the release key (i.e. it 
should not require a manual uninstall) that contains this change. If you have a 
few minutes to spare, I'd be happy if you could try it out.


```

Original comment by `philipp.kern` on 17 Sep 2012 at 3:56
- Changed state: **Fixed**

Attachments:
- [kitcard-reader-0.9.1-interim.apk](https://storage.googleapis.com/google-code-attachments/kitcard-reader/issue-5/comment-4/kitcard-reader-0.9.1-interim.apk)

**Comment by GoogleCodeExporter** [comment]
```
"Works" :) (doesn't crash but tells me I need to have my card "umkodiert")

Cheers
```

Original comment by `ps.si...@gmail.com` on 17 Sep 2012 at 4:06

**Comment by GoogleCodeExporter** [comment]
```
Yay, thanks. :)
```

Original comment by `philipp.kern` on 17 Sep 2012 at 4:20
- Changed state: **Verified**
